import { WarehouseLayoutConfig, WarehouseLayoutElement, WarehousePassage } from "@/lib/db/schema";

/**
 * Creates a default enterprise event logistics layout blueprint
 * fitted to the warehouse's zones and standard operational passages.
 */
export function generateDefaultWarehouseLayout(warehouseName: string, zones: any[] = []): WarehouseLayoutConfig {
    const audioZone = zones.find(z => z.code?.includes("AUD") || z.name?.toLowerCase().includes("audio")) || { id: "zone-audio", code: "ZN-AUD-A", color: "#3b82f6" };
    const lgtZone = zones.find(z => z.code?.includes("LGT") || z.name?.toLowerCase().includes("lighting")) || { id: "zone-lighting", code: "ZN-LGT-B", color: "#f59e0b" };
    const stgZone = zones.find(z => z.code?.includes("STG") || z.name?.toLowerCase().includes("staging")) || { id: "zone-staging", code: "ZN-STG-C", color: "#10b981" };
    const ledZone = zones.find(z => z.code?.includes("LED") || z.name?.toLowerCase().includes("video")) || { id: "zone-led", code: "ZN-LED-D", color: "#8b5cf6" };
    const qcZone = zones.find(z => z.code?.includes("QC") || z.name?.toLowerCase().includes("repair")) || { id: "zone-qc", code: "ZN-QC-LAB", color: "#ef4444" };

    const elements: WarehouseLayoutElement[] = [
        // ─── Loading Docks & Intake Ports (Top Row) ───
        {
            id: "dock-01",
            type: "dock_door",
            x: 2,
            y: 1,
            width: 5,
            height: 3,
            label: "Loading Bay 01 (Outbound Heavy)",
            color: "#10b981",
            status: "active",
        },
        {
            id: "dock-02",
            type: "dock_door",
            x: 8,
            y: 1,
            width: 5,
            height: 3,
            label: "Loading Bay 02 (Cross-Dock Fast-Track)",
            color: "#3b82f6",
            status: "active",
        },
        {
            id: "dock-03",
            type: "dock_door",
            x: 14,
            y: 1,
            width: 5,
            height: 3,
            label: "Loading Bay 03 (Inbound Returns)",
            color: "#f59e0b",
            status: "active",
        },
        {
            id: "dock-04",
            type: "dock_door",
            x: 20,
            y: 1,
            width: 5,
            height: 3,
            label: "Loading Bay 04 (Inter-Hub Transit)",
            color: "#6366f1",
            status: "active",
        },
        {
            id: "qc-lab-01",
            type: "quarantine",
            x: 26,
            y: 1,
            width: 6,
            height: 4,
            label: "Technical QC & Decontamination Lab",
            zoneId: qcZone.id,
            zoneCode: qcZone.code,
            color: "#ef4444",
            status: "active",
        },

        // ─── Staging Buffers (Holding Pads) ───
        {
            id: "stage-pad-01",
            type: "staging",
            x: 2,
            y: 6,
            width: 10,
            height: 3,
            label: "Outbound Flight Case Staging Pad A",
            zoneId: stgZone.id,
            zoneCode: stgZone.code,
            color: "#10b981",
            status: "active",
        },
        {
            id: "stage-pad-02",
            type: "staging",
            x: 13,
            y: 6,
            width: 10,
            height: 3,
            label: "Inbound Check-in & Sortation Pad B",
            zoneId: stgZone.id,
            zoneCode: stgZone.code,
            color: "#f59e0b",
            status: "active",
        },
        {
            id: "packing-table-01",
            type: "packing_station",
            x: 24,
            y: 6,
            width: 8,
            height: 3,
            label: "Kitting & Flight Case Audit Station",
            color: "#eab308",
            status: "active",
        },

        // ─── Aisle A: Audio & Acoustics Heavy Racks (Double Run) ───
        {
            id: "rack-aud-01",
            type: "rack",
            x: 3,
            y: 11,
            width: 5,
            height: 2,
            label: "Rack AUD-01 (Line Arrays)",
            rackCode: "RCK-AUD-01",
            aisle: "Aisle A",
            zoneId: audioZone.id,
            zoneCode: audioZone.code,
            levels: 4,
            capacityPerLevel: 25,
            color: audioZone.color,
            status: "active",
        },
        {
            id: "rack-aud-02",
            type: "rack",
            x: 9,
            y: 11,
            width: 5,
            height: 2,
            label: "Rack AUD-02 (Subwoofers)",
            rackCode: "RCK-AUD-02",
            aisle: "Aisle A",
            zoneId: audioZone.id,
            zoneCode: audioZone.code,
            levels: 4,
            capacityPerLevel: 20,
            color: audioZone.color,
            status: "active",
        },
        {
            id: "rack-aud-03",
            type: "rack",
            x: 15,
            y: 11,
            width: 5,
            height: 2,
            label: "Rack AUD-03 (Digital Consoles)",
            rackCode: "RCK-AUD-03",
            aisle: "Aisle A",
            zoneId: audioZone.id,
            zoneCode: audioZone.code,
            levels: 4,
            capacityPerLevel: 15,
            color: audioZone.color,
            status: "active",
        },
        {
            id: "rack-aud-04",
            type: "rack",
            x: 21,
            y: 11,
            width: 5,
            height: 2,
            label: "Rack AUD-04 (Microphones & RF)",
            rackCode: "RCK-AUD-04",
            aisle: "Aisle A",
            zoneId: audioZone.id,
            zoneCode: audioZone.code,
            levels: 4,
            capacityPerLevel: 30,
            color: audioZone.color,
            status: "active", // Empty rack candidate
        },

        // ─── Aisle B: Lighting & Moving Heads (Double Run) ───
        {
            id: "rack-lgt-01",
            type: "rack",
            x: 3,
            y: 15,
            width: 5,
            height: 2,
            label: "Rack LGT-01 (Profile Fixtures)",
            rackCode: "RCK-LGT-01",
            aisle: "Aisle B",
            zoneId: lgtZone.id,
            zoneCode: lgtZone.code,
            levels: 4,
            capacityPerLevel: 25,
            color: lgtZone.color,
            status: "active",
        },
        {
            id: "rack-lgt-02",
            type: "rack",
            x: 9,
            y: 15,
            width: 5,
            height: 2,
            label: "Rack LGT-02 (Beam & Wash)",
            rackCode: "RCK-LGT-02",
            aisle: "Aisle B",
            zoneId: lgtZone.id,
            zoneCode: lgtZone.code,
            levels: 4,
            capacityPerLevel: 25,
            color: lgtZone.color,
            status: "active",
        },
        {
            id: "rack-lgt-03",
            type: "rack",
            x: 15,
            y: 15,
            width: 5,
            height: 2,
            label: "Rack LGT-03 (Strobe & Blinders)",
            rackCode: "RCK-LGT-03",
            aisle: "Aisle B",
            zoneId: lgtZone.id,
            zoneCode: lgtZone.code,
            levels: 4,
            capacityPerLevel: 20,
            color: lgtZone.color,
            status: "active",
        },
        {
            id: "rack-lgt-04",
            type: "rack",
            x: 21,
            y: 15,
            width: 5,
            height: 2,
            label: "Rack LGT-04 (Followspots & FX)",
            rackCode: "RCK-LGT-04",
            aisle: "Aisle B",
            zoneId: lgtZone.id,
            zoneCode: lgtZone.code,
            levels: 4,
            capacityPerLevel: 15,
            color: lgtZone.color,
            status: "dead_spot", // Simulated dead spot / cold storage
        },

        // ─── Aisle C: LED Video & Cantilever Truss Rigging ───
        {
            id: "rack-led-01",
            type: "rack",
            x: 3,
            y: 19,
            width: 5,
            height: 2,
            label: "Rack LED-01 (Outdoor 3.9mm Panels)",
            rackCode: "RCK-LED-01",
            aisle: "Aisle C",
            zoneId: ledZone.id,
            zoneCode: ledZone.code,
            levels: 3,
            capacityPerLevel: 40,
            color: ledZone.color,
            status: "active",
        },
        {
            id: "rack-led-02",
            type: "rack",
            x: 9,
            y: 19,
            width: 5,
            height: 2,
            label: "Rack LED-02 (Indoor 2.6mm High-Res)",
            rackCode: "RCK-LED-02",
            aisle: "Aisle C",
            zoneId: ledZone.id,
            zoneCode: ledZone.code,
            levels: 3,
            capacityPerLevel: 40,
            color: ledZone.color,
            status: "active",
        },
        {
            id: "rack-stg-01",
            type: "rack",
            x: 15,
            y: 19,
            width: 5,
            height: 2,
            label: "Rack RIG-01 (Heavy Cantilever Truss)",
            rackCode: "RCK-RIG-01",
            aisle: "Aisle C",
            zoneId: stgZone.id,
            zoneCode: stgZone.code,
            levels: 3,
            capacityPerLevel: 30,
            color: stgZone.color,
            status: "active",
        },
        {
            id: "rack-stg-02",
            type: "rack",
            x: 21,
            y: 19,
            width: 5,
            height: 2,
            label: "Rack RIG-02 (Electric Chain Hoists)",
            rackCode: "RCK-RIG-02",
            aisle: "Aisle C",
            zoneId: stgZone.id,
            zoneCode: stgZone.code,
            levels: 3,
            capacityPerLevel: 20,
            color: stgZone.color,
            status: "active",
        },

        // ─── Obstacles / Structural Columns ───
        {
            id: "pillar-01",
            type: "obstacle",
            x: 8,
            y: 13,
            width: 1,
            height: 1,
            label: "Pillar A1",
            color: "#475569",
        },
        {
            id: "pillar-02",
            type: "obstacle",
            x: 20,
            y: 13,
            width: 1,
            height: 1,
            label: "Pillar A2",
            color: "#475569",
        },
        {
            id: "pillar-03",
            type: "obstacle",
            x: 8,
            y: 17,
            width: 1,
            height: 1,
            label: "Pillar B1",
            color: "#475569",
        },
        {
            id: "pillar-04",
            type: "obstacle",
            x: 20,
            y: 17,
            width: 1,
            height: 1,
            label: "Pillar B2",
            color: "#475569",
        },
    ];

    const passages: WarehousePassage[] = [
        {
            id: "pass-main-forklift",
            name: "Main Arterial Forklift Highway (Aisle 0)",
            type: "forklift_main",
            x1: 1,
            y1: 9,
            x2: 32,
            y2: 10,
            width: 2,
        },
        {
            id: "pass-cross-west",
            name: "West Cross-Aisle",
            type: "cross_aisle",
            x1: 1,
            y1: 10,
            x2: 2,
            y2: 22,
            width: 1.5,
        },
        {
            id: "pass-aisle-a",
            name: "Aisle A Picking Corridor",
            type: "pedestrian_lane",
            x1: 2,
            y1: 13,
            x2: 27,
            y2: 14,
            width: 1.5,
        },
        {
            id: "pass-aisle-b",
            name: "Aisle B Picking Corridor",
            type: "pedestrian_lane",
            x1: 2,
            y1: 17,
            x2: 27,
            y2: 18,
            width: 1.5,
        },
        {
            id: "pass-cross-east",
            name: "East Cross-Aisle",
            type: "cross_aisle",
            x1: 27,
            y1: 10,
            x2: 28,
            y2: 22,
            width: 1.5,
        },
    ];

    return {
        dimensions: {
            widthMeters: 34,
            lengthMeters: 23,
            gridCols: 34,
            gridRows: 23,
            gridScaleMeters: 1,
        },
        elements,
        passages,
        updatedAt: new Date().toISOString(),
        version: 1,
    };
}
